stages:
  - build
  - release

before_script:
  - export DOCKER_BUILDKIT=1

build:
  image: docker
  stage: build
  script:
    - docker image build --target build .

release:
  image: docker
  stage: release
  dependencies:
    - build
  only:
    - master
  script:
    - docker image build --target artifacts .
  artifacts:
    paths:
      - out
