version: '3.4'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/nginx

services:
  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: ./app
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/app
    volumes:
      - ./app:/usr/src/app:rw,cached
      - /usr/src/app/node_modules
      - app-static:/static:rw
      - app-desktop:/desktop:rw

  nginx:
    build:
      context: ./nginx
      <<: *cache
    depends_on:
      - app
    volumes:
      - /usr/src/nginx/cache:/cache:rw
      - app-static:/static:ro
      - app-desktop:/desktop:ro
    ports:
      - "8000:8000"
      - "80:80"

volumes:
  app-static: {}
  app-desktop: {}
