name: Build

on:
  release:
    types:
      - created

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: "latest"
  PACKAGE_NAME: 'labwork'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])
          IMAGE_NAME="docker.pkg.github.com/${IMAGE_REPOSITORY}/${{ env.PACKAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Login
        env:
          USER_NAME: ${{ github.actor }}
          USER_PASSWORD: ${{ github.token }}
        run: |
          echo $USER_PASSWORD | docker login https://docker.pkg.github.com -u $USER_NAME --password-stdin

      - name: Push cache
        run: |
          docker pull ${{ env.IMAGE_NAME }}

      - name: Install
        run: docker build --target node_modules --cache-from ${{ env.IMAGE_NAME }} .

      - name: Build web app
        run: docker build --target build --cache-from ${{ env.IMAGE_NAME }} .

      - name: Build desktop app
        run: docker build --target package --cache-from ${{ env.IMAGE_NAME }} .

      - name: Prepare artifacts
        run: docker build --target artifacts --cache-from ${{ env.IMAGE_NAME }} --build-arg BUILDKIT_INLINE_CACHE=1 -t ${{ env.IMAGE_NAME }} .

      - name: Collect artifacts
        run: docker build --target artifacts --cache-from ${{ env.IMAGE_NAME }} -o artifacts .

      - name: LS artifacts
        run: ls artifacts

      - name: Upload web app
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: artifacts/dist

      - name: Upload linux app
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            artifacts/linux-setup
            artifacts/net-labwork-linux-x64

      - name: Upload windows app
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            artifacts/win-setup
            artifacts/net-labwork-win32-x64

      - name: Upload mac os app
        uses: actions/upload-artifact@v2
        with:
          name: mac_os
          path: artifacts/net-labwork-darwin-x64

      - name: Login
        env:
          USER_NAME: ${{ github.actor }}
          USER_PASSWORD: ${{ github.token }}
        run: |
          echo $USER_PASSWORD | docker login https://docker.pkg.github.com -u $USER_NAME --password-stdin

      - name: Push
        run: |
          docker push ${{ env.IMAGE_NAME }}
