name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Install
        run: docker build --target node_modules --cache-from labwork .

      - name: Build web app
        run: docker build --target build --cache-from labwork .

      - name: Build desktop app
        run: docker build --target package --cache-from labwork .

      - name: Get artifacts
        run: docker build --target artifacts --build-arg BUILDKIT_INLINE_CACHE=1 -t labwork -o artifacts .

      - name: LS artifacts
        run: ls artifacts

      - name: Upload web app
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: artifacts/dist

      - name: Upload linux app
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            artifacts/linux-setup
            artifacts/net-labwork-linux-x64

      - name: Upload windows app
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            artifacts/win-setup
            artifacts/net-labwork-win32-x64

      - name: Upload mac os app
        uses: actions/upload-artifact@v2
        with:
          name: mac_os
          path: artifacts/net-labwork-darwin-x64
